### ISSUE TITLE
To Do: units, common name, and fill value support

### ISSUE THREAD

**Issue by narock** [narock/datacubes#2]
hasCommonName, hasUnits, and hasFillValue are not yet implemented

**Comment by ashepherd** [comment]
hey, good point about this. i forgot we don't have this info in GeoLink, and I just checked our own ontology and we don't have it their either. FOr now, you can use this JSON endpoint foreach dataset to get this info.

http://www.bco-dmo.org/api/dataset/2333/parameters
http://www.bco-dmo.org/api/dataset/552076/parameters

and look for the 'no_data_value' attribute for each parameter.

We don't do a great job of units either, but you can find that from our Linked Data:

For a parameter, http://lod.bco-dmo.org/id/dataset-parameter/552086, you can walk down to odo:hasUnitOfMeasure > rdf:value 
and for the common name, you have the local parameter name at: skos:prefLabel or a more common name at [ odo:isInstanceOf skos:prefLabel ]

(See: http://lod.bco-dmo.org/browse/?query=SELECT+DISTINCT+%3Fproperty+%3FhasValue+%3FisValueOf%0D%0AWHERE+%7B%0D%0A++%7B+%3Chttp%3A%2F%2Flod.bco-dmo.org%2Fid%2Fdataset-parameter%2F552086%3E+%3Fproperty+%3FhasValue+%7D%0D%0A++UNION%0D%0A++%7B+%3FisValueOf+%3Fproperty+%3Chttp%3A%2F%2Flod.bco-dmo.org%2Fid%2Fdataset-parameter%2F552086%3E+%7D%0D%0A%7D%0D%0AORDER+BY+%28%21BOUND%28%3FhasValue%29%29+%3Fproperty+%3FhasValue+%3FisValueOf )

**Comment by narock** [comment]
Fixed in the June 1, 2017 commit
